### PR TITLE
Upload picture of james

### PR DESCRIPTION
**Pull request by jrp90**
## Description of change
-- Description of Code Changes or new blog post --

## Authors
-- Please put full names & if possible GitHub handles -
James Pettifer (jrp90)

### CODE REVIEW

**Comment by jrp90** [comment]
Oh that's annoying - only got my phone on me today and seems the right way in my file manager so 😕

**Comment by jrp90** [comment]
I'll fix in a bit 👍

**Comment by jrp90** [comment]
ok that's better :)

**Comment by AnnaDodson** [comment]
That happened to me too! Looks great now

**Pull request merged**
