### PR TITLE
Make `localhost` into a link

### PR DESCRIPTION
**Pull request by annashipman**
I've raised this PR separately to #9 because I think you might want one and not the other; this way you don't have to accept both if you don't want both!

## Description of change
This could make it easier for people to see how to run it, and means you don't need the extra line of explanation.

## Authors
Anna Shipman @annashipman

### CODE REVIEW

**Comment by wordshaker** [comment]
Accepted the first one :) Thanks again

**Comment by annashipman** [comment]
Hi @wordshaker! Thanks for the quick response!

I just wanted to clarify that this one is different to #9 - this PR adds a link for running the server locally. So you could accept both - they don't conflict.

No worries if you still don’t want it, I just wanted to clarify as I think I hadn't explained myself in this one very well.

Thanks for merging #9!

**Comment by wordshaker** [comment]
Ah yes! Sorry - I didn't spot that. 
Happy to merge this too.

**Comment by annashipman** [comment]
Great! Thank you!

**Pull request merged**
